apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-actuator-4-k8s-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-actuator-4-k8s-demo-pods
  template:
    metadata:
      labels:
        app: spring-actuator-4-k8s-demo-pods
    spec:
      containers:
        - name: spring-actuator-4-k8s-demo
          image: library/spring-actuator-4-k8s-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: spring-actuator-4-k8s-demo-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: spring-actuator-4-k8s-demo-pods
